apiVersion: apps/v1
kind: Deployment
metadata:
  name: approval-operator
  namespace: hypercloud4-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: approval-operator
  template:
    metadata:
      labels:
        name: approval-operator
    spec:
      serviceAccountName: approval-operator
      containers:
        - name: approval-operator
          image: 172.22.11.2:30500/approval-operator:test #TODO: Should be public repository
          command:
          - approval-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "approval-operator"
            - name: WEBHOOK_PORT
              value: "9443"
