kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: approval-operator
subjects:
- kind: ServiceAccount
  name: approval-operator
  namespace: hypercloud4-system
roleRef:
  kind: ClusterRole
  name: approval-operator
  apiGroup: rbac.authorization.k8s.io
