apiVersion: v1
kind: Service
metadata:
  name: approval-operator
  namespace: hypercloud4-system
spec:
  selector:
    name: approval-operator
  ports:
  - port: 443
    targetPort: 9443
    name: approval-webhook
  - port: 8081
    targetPort: 8081
    name: approval-controller
