apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating.approval.tmax.io
  labels:
    app.kubernetes.io/component: webhook
    app.kubernetes.io/instance: default
    app.kubernetes.io/part-of: approval
webhooks:
  - clientConfig:
      service:
        name: approval-webhook
        namespace: approval
    failurePolicy: Fail
    sideEffects: None
    name: validating.approval.tmax.io
